title: Status Incubate
subtitle: "Incubating Projects that are Building Web3"
description: "We’re advancing the Ethereum ecosystem by contributing to the growth of early stage, open source blockchain projects that share our values."
author: Incubate
language: en
timezone: UTC

url: https://dev-incubate.status.im/
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  branch: gh-pages
  name: status-im-auto
  repo: git@github.com:status-im/incubate.status.im.git

theme_config:
    favicon: img/logo-32.png

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
twitter: ethstatus
github: staus-im
